part of "models.dart";
/*
@HiveType(typeId: HiveAdapterTypeId.userAccount)
class Account {
  Account({
    required this.access_token,
    required this.refresh_token,
    required this.user
  });

  @HiveField(0)
  String access_token;
  @HiveField(1)
  String refresh_token;
  @HiveField(2)
  String token_type;
  @HiveField(3)
  User user;
}

class User {

    User.fromJson(Map<dynamic,dynamic> data){
    this.id = data[id];
  };

  Map profile_image_urls = {"px_16x16": "", "px_50x50": "", "px_170x170": ""};

  String id;

  String name;

  String account;

  String mail_address;

  bool is_premium;

  String x_restrict;

  bool is_mail_authorized;

  bool require_policy_agreement;
}
*/

// Generated by Json2Dart

@HiveType(typeId: HiveAdapterTypeId.userAccount)
class Account {
  @HiveField(0)
  String? accessToken;
  @HiveField(1)
  String? tokenType;
  @HiveField(2)
  String? refreshToken;
  @HiveField(3)
  Map? user;

  Account({this.accessToken, this.tokenType, this.refreshToken, this.user});

  Account.fromJson(Map<String, dynamic> json) {
    accessToken = json["access_token"];
    tokenType = json["token_type"];
    refreshToken = json["refresh_token"];
    user = json["user"];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["access_token"] = accessToken;
    data["token_type"] = tokenType;
    data["refresh_token"] = refreshToken;
    data["user"] = user;
    return data;
  }

  @override
  String toString() {
    return toJson().toString();
  }
}

/*
class User {
  ProfileImageUrls? profileImageUrls;
  String? id;
  String? name;
  String? account;
  String? mailAddress;
  bool? isPremium;
  int? xRestrict;
  bool? isMailAuthorized;
  bool? requirePolicyAgreement;

  User(
      {this.profileImageUrls,
      this.id,
      this.name,
      this.account,
      this.mailAddress,
      this.isPremium,
      this.xRestrict,
      this.isMailAuthorized,
      this.requirePolicyAgreement});

  User.fromJson(Map<String, dynamic> json) {
    profileImageUrls = json["profile_image_urls"] == null
        ? null
        : ProfileImageUrls.fromJson(json["profile_image_urls"]);
    id = json["id"];
    name = json["name"];
    account = json["account"];
    mailAddress = json["mail_address"];
    isPremium = json["is_premium"];
    xRestrict = json["x_restrict"];
    isMailAuthorized = json["is_mail_authorized"];
    requirePolicyAgreement = json["require_policy_agreement"];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (profileImageUrls != null) {
      data["profile_image_urls"] = profileImageUrls?.toJson();
    }
    data["id"] = id;
    data["name"] = name;
    data["account"] = account;
    data["mail_address"] = mailAddress;
    data["is_premium"] = isPremium;
    data["x_restrict"] = xRestrict;
    data["is_mail_authorized"] = isMailAuthorized;
    data["require_policy_agreement"] = requirePolicyAgreement;
    return data;
  }
}

class ProfileImageUrls {
  String? px16X16;
  String? px50X50;
  String? px170X170;

  ProfileImageUrls({this.px16X16, this.px50X50, this.px170X170});

  ProfileImageUrls.fromJson(Map<String, dynamic> json) {
    px16X16 = json["px_16x16"];
    px50X50 = json["px_50x50"];
    px170X170 = json["px_170x170"];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["px_16x16"] = px16X16;
    data["px_50x50"] = px50X50;
    data["px_170x170"] = px170X170;
    return data;
  }
}
*/